apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../letsencrypt-base

configMapGenerator:
  - name: le-params
    literals:
      - email=you@example.com

replacements:
  - source: {kind: ConfigMap, name: le-params, fieldPath: data.email}
    targets:
      - select: {kind: ClusterIssuer, name: letsencrypt}
        fieldPaths: [spec.acme.email]
