apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../home
patches:
  - path: patch-cilium-hubble-issuer.yaml
  - path: patch-minio-issuer.yaml
  - path: patch-minio-console-issuer.yaml
