apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hello-web
spec:
  secretName: hello-web-tls
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
  dnsNames:
    - placeholder.local

