apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-web
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts: ["placeholder.local"]
      secretName: hello-web-tls
  rules:
    - host: "placeholder.local"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-web
                port:
                  number: 80

