kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 31514
        hostPort: 31514
        protocol: TCP
      - containerPort: 30313
        hostPort: 30313
        protocol: TCP
