{{- if .Values.tls.enabled -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "apps-hello.name" . }}
  labels:
{{ include "apps-hello.labels" . | indent 4 }}
spec:
  secretName: {{ .Values.ingress.tlsSecretName | default (printf "%s-tls" (include "apps-hello.name" .)) | quote }}
  issuerRef:
    name: {{ .Values.tls.issuerName | default "selfsigned" | quote }}
    kind: ClusterIssuer
  dnsNames:
{{- range $d := (.Values.tls.dnsNames | default (list .Values.ingress.host)) }}
    - {{ $d | quote }}
{{- end }}
{{- end -}}

