apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apps-hello.name" . }}
  labels:
{{ include "apps-hello.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "apps-hello.name" . | quote }}
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "apps-hello.name" . | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
    spec:
      containers:
        - name: web
          image: {{ printf "%s:%s" (.Values.image.repository | default "docker.io/nginx") (.Values.image.tag | default "latest") | quote }}
          ports:
            - name: http
              containerPort: 80
