{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "apps-hello.name" . }}
  labels:
{{ include "apps-hello.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className | default "nginx" | quote }}
{{- range $k, $v := (.Values.ingress.annotations | default dict) }}
    {{ $k }}: {{ $v | quote }}
{{- end }}
{{- if .Values.auth.enabled }}
    nginx.ingress.kubernetes.io/auth-url: {{ printf "https://%s/oauth2/auth" .Values.auth.oauthHost | quote }}
    nginx.ingress.kubernetes.io/auth-signin: {{ printf "https://%s/oauth2/start?rd=$scheme://$host$request_uri" .Values.auth.oauthHost | quote }}
{{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | default "nginx" | quote }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ .Values.ingress.tlsSecretName | default (printf "%s-tls" (include "apps-hello.name" .)) | quote }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "apps-hello.name" . }}
                port:
                  number: {{ .Values.service.port | default 80 }}
{{- end -}}

