apiVersion: v1
kind: Service
metadata:
  name: {{ include "apps-hello.name" . }}
  labels:
{{ include "apps-hello.labels" . | indent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "apps-hello.name" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
  ports:
    - name: http
      port: {{ .Values.service.port | default 80 }}
      targetPort: http
