apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${APP_NAME}
  namespace: ${APP_NS}
spec:
  secretName: ${TLS_SECRET}
  issuerRef:
    name: ${ISSUER}
    kind: ClusterIssuer
  dnsNames:
    - ${HOST}

