apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../base/clickstack
patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: clickstack
    patch: |-
      - op: replace
        path: /spec/values/hyperdx/frontendUrl
        value: https://clickstack.homelab.swhurl.com
      - op: replace
        path: /spec/values/hyperdx/ingress/host
        value: clickstack.homelab.swhurl.com
      - op: replace
        path: /spec/values/hyperdx/ingress/annotations/cert-manager.io~1cluster-issuer
        value: letsencrypt-prod
