apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-web
  namespace: "${APP_NAMESPACE}"
  labels:
    app.kubernetes.io/name: hello-web
    app.kubernetes.io/instance: hello-web
    platform.swhurl.io/managed: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-web
      app.kubernetes.io/instance: hello-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello-web
        app.kubernetes.io/instance: hello-web
        platform.swhurl.io/managed: "true"
    spec:
      containers:
        - name: web
          image: docker.io/nginx:1.25-alpine
          ports:
            - name: http
              containerPort: 80
