apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-web
  namespace: apps-staging
  labels:
    app.kubernetes.io/name: hello-web
    app.kubernetes.io/instance: hello-web
    platform.swhurl.io/managed: "true"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/auth-url: https://oauth.homelab.swhurl.com/oauth2/auth
    nginx.ingress.kubernetes.io/auth-signin: https://oauth.homelab.swhurl.com/oauth2/start?rd=$scheme://$host$request_uri
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - staging-hello.homelab.swhurl.com
      secretName: hello-web-tls
  rules:
    - host: staging-hello.homelab.swhurl.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-web
                port:
                  number: 80
