apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps-prod
resources:
  - ../../../../base/apps/example
patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: hello-web
    patch: |-
      - op: replace
        path: /spec/values/tls/issuerName
        value: letsencrypt-prod
