apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps-staging
resources:
  - ../../base
patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: hello-web
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: staging.hello.homelab.swhurl.com
      - op: replace
        path: /spec/tls/0/hosts/0
        value: staging.hello.homelab.swhurl.com
      - op: replace
        path: /metadata/annotations/nginx.ingress.kubernetes.io~1auth-url
        value: https://oauth.homelab.swhurl.com/oauth2/auth
      - op: replace
        path: /metadata/annotations/nginx.ingress.kubernetes.io~1auth-signin
        value: https://oauth.homelab.swhurl.com/oauth2/start?rd=$scheme://$host$request_uri
  - target:
      group: cert-manager.io
      version: v1
      kind: Certificate
      name: hello-web
    patch: |-
      - op: replace
        path: /spec/issuerRef/name
        value: letsencrypt-staging
      - op: replace
        path: /spec/dnsNames/0
        value: staging.hello.homelab.swhurl.com
