apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - clusterissuer-selfsigned.yaml
  - clusterissuer-letsencrypt-staging.yaml
  - clusterissuer-letsencrypt-prod.yaml
  - clusterissuer-letsencrypt.yaml
