apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps-prod
resources:
  - ../../base
patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: hello-web
    patch: |-
      - op: replace
        path: /spec/values/tls/issuerName
        value: letsencrypt-prod
      - op: replace
        path: /spec/values/ingress/host
        value: hello.homelab.swhurl.com
      - op: replace
        path: /spec/values/tls/dnsNames/0
        value: hello.homelab.swhurl.com
      - op: replace
        path: /spec/values/auth/oauthHost
        value: oauth.homelab.swhurl.com
