apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homelab-flux-sources
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: swhurl-platform
  path: ./cluster/flux/sources
  prune: true
  wait: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homelab-flux-stack
  namespace: flux-system
spec:
  dependsOn:
    - name: homelab-flux-sources
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: swhurl-platform
  path: ./cluster/overlays/homelab/flux
  prune: true
  wait: true
  timeout: 20m
