apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/namespaces
  - ../../base/cilium
  - ../../base/cert-manager
  - ../../base/cert-manager/issuers
  - providers/ingress-nginx
  - ../../base/oauth2-proxy
  - ../../base/clickstack
  - ../../base/otel
  - providers/storage-minio
  - apps/staging
