apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Phase-in as components are migrated to GitOps.
  # - ../../base
  # - providers/ingress-traefik
  # - providers/storage-minio
