apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []

# Phase-in as components are migrated to GitOps.
# - ../../base
# Choose one ingress provider:
# - providers/ingress-traefik
# - providers/ingress-nginx
# Choose one object storage provider:
# - providers/storage-minio
# - providers/storage-ceph
