apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../base/storage/minio
patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: minio
    patch: |-
      - op: replace
        path: /spec/values/ingress/annotations/cert-manager.io~1cluster-issuer
        value: letsencrypt-staging
      - op: replace
        path: /spec/values/ingress/hosts/0
        value: minio.homelab.swhurl.com
      - op: replace
        path: /spec/values/ingress/tls/0/hosts/0
        value: minio.homelab.swhurl.com
      - op: replace
        path: /spec/values/consoleIngress/annotations/cert-manager.io~1cluster-issuer
        value: letsencrypt-staging
      - op: replace
        path: /spec/values/consoleIngress/hosts/0
        value: minio-console.homelab.swhurl.com
      - op: replace
        path: /spec/values/consoleIngress/tls/0/hosts/0
        value: minio-console.homelab.swhurl.com
