apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../namespaces
  - ../../runtime-inputs
  - ../../cilium/base
  - ../../metrics-server/base
  - ../../cert-manager/base
  - ../../cert-manager/issuers
  - ../../ingress-nginx/base
  - ../../storage/minio/base
